stages:
- name: stage1
  steps:
  - runScriptConfig:
      image: ubuntu:18.04
      shellScript: echo "haha"
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: c-fqfdk:hwchiu-cicd-app
      version: 0.1.0
      name: rancher-app
      targetNamespace: hwchiu
timeout: 60
notification: {}
